### ISSUE TITLE
Textbook Solutions Screenshots

### ISSUE THREAD

**Issue by misternobody1337** [apekros/chegg_discord_bot#1]
Great work, however, textbook solutions can not take screenshots which makes the bot broke and others can not use it :/

**Comment by apekros** [comment]
It doesn't take screenshots. It takes the pictures matching the cheggcdn domain which doesn't happen for textbook solutions. You can modify it easily.

**Comment by misternobody1337** [comment]
Also, if someone typed wrong and the bot process it, the bot does not stop which mean the next person unable to use it. On discord it said, wait for your turn

**Comment by apekros** [comment]
The source is there, it's just a learning resource not something that can be used for profit on Discord like many do. If you want to do so fix up the issues.

**Comment by misternobody1337** [comment]
I mean I'm using it among friends to help with homeworks and assignments, not to make profit on discord like others.
